### PR TITLE
add ability to set icons for buttons in group

### PR DESCRIPTION
**Pull request by josefbehr**

### CODE REVIEW

**Comment by andrewdwallo** [comment]
@josefbehr Thanks for the PR! I think if we are going to go ahead and allow icons, it would be nice if users can also customize the icon positions and their size. If possible, would you be willing to update this in order for that to happen?

**Comment by josefbehr** [comment]
@andrewdwallo just added those

**Comment by andrewdwallo** [comment]
Awesome! Works great. Would you like to update the documentation?

**Comment by josefbehr** [comment]
@andrewdwallo I have updated the README

**Comment by andrewdwallo** [comment]
Thank you!

**Pull request merged**
